document.addEventListener("DOMContentLoaded", function () {
  const iniciarButton = document.getElementById("iniciar");
  const pararButton = document.getElementById("parar");
  const reiniciarButton = document.getElementById("reiniciar");
  const imagemSorteada = document.getElementById("imagemSorteada");

  const imagens = [
    "007 Shitou - The Duel (Japan).png",
    "10 Super Jogos (Brazil).png",
    "16 Zhang Ma Jiang (China) (Unl).png",
    "16t (Japan) (SegaNet).png",
    "2020 Nen Super Baseball (Japan).png",
    "3 Ninjas Kick Back (USA).png",
    "6-Pak (USA).png",
    "688 Attack Sub (USA, Europe).png",
    "A Ressha de Ikou MD (Japan).png",
    "Aa Harimanada (Japan).png",
    "Aaahh!!! Real Monsters (Europe).png",
    "Aaahh!!! Real Monsters (USA) (Beta) (1995-07-07).png",
    "Aaahh!!! Real Monsters (USA).png",
    "Action 52 (USA) (Alt 1) (Unl).png",
    "Action 52 (USA) (Unl).png",
    "Addams Family Values (Europe) (En,Fr,De).png",
    "Addams Family, The (USA) (Beta) (Alt 1).png",
    "Addams Family, The (USA) (Beta).png",
    "Addams Family, The (USA, Europe).png",
    "Advanced Busterhawk Gleylancer (Japan).png",
    "Advanced Daisenryaku - Deutsch Dengeki Sakusen (Japan) (Rev A).png",
    "Adventures of Batman & Robin, The (Europe).png",
    "Adventures of Batman & Robin, The (USA).png",
    "Adventures of Mighty Max, The (Europe).png",
    "Adventures of Mighty Max, The (USA).png",
    "Adventures of Rocky and Bullwinkle and Friends, The (USA).png",
    "Adventurous Boy - Mao Xian Xiao Zi (China) (Unl).png",
    "Aero Blasters (Japan).png",
    "Aero the Acro-Bat (Europe).png",
    "Aero the Acro-Bat (USA).png",
    "Aero the Acro-Bat 2 (Europe).png",
    "Aero the Acro-Bat 2 (USA).png",
    "Aerobiz (USA).png",
    "Aerobiz Supersonic (USA).png",
    "After Burner II (Japan).png",
    "After Burner II (USA, Europe).png",
    "Air Buster (USA).png",
    "Air Diver (Japan).png",
    "Air Diver (USA).png",
    "Air Management - Oozora ni Kakeru (Japan).png",
    "Air Management II - Koukuuou o Mezase (Japan).png",
    "Aladdin (Europe).png",
    "Aladdin (Japan).png",
    "Aladdin (USA) (Beta).png",
    "Aladdin (USA).png",
    "Alex Kidd - Cheongong Maseong (Korea).png",
    "Alex Kidd - Tenkuu Majou (Japan).png",
    "Alex Kidd in the Enchanted Castle (Europe) (Rev A).png",
    "Alex Kidd in the Enchanted Castle (Europe).png",
    "Alex Kidd in the Enchanted Castle (USA).png",
    "Alien 3 (USA, Europe) (Rev A).png",
    "Alien 3 (USA, Europe).png",
    "Alien Soldier (Europe).png",
    "Alien Soldier (Japan).png",
    "Alien Storm (World).png",
    "Alisia Dragoon (Europe).png",
    "Alisia Dragoon (Japan).png",
    "Alisia Dragoon (USA).png",
    "Altered Beast (USA, Europe).png",
    "American Gladiators (USA).png",
    "Andre Agassi Tennis (Europe).png",
    "Andre Agassi Tennis (USA) (Beta).png",
    "Andre Agassi Tennis (USA).png",
    "Animaniacs (Europe) (En,Fr,De).png",
    "Animaniacs (USA).png",
    "Another World (Europe).png",
    "Aoki Ookami to Shiroki Mejika - Genchou Hishi (Japan).png",
    "Aq Renkan Awa (China) (Unl).png",
    "Aquatic Games Starring James Pond and the Aquabats, The (USA, Europe).png",
    "Arcade Classics (USA, Europe).png",
    "Arch Rivals - The Arcade Game (USA, Europe).png",
    "Arcus Odyssey (Japan).png",
    "Arcus Odyssey (USA).png",
    "Ariel the Little Mermaid (USA, Europe).png",
    "Arnold Palmer Tournament Golf (USA, Europe).png",
    "Arrow Flash (Japan, Europe).png",
    "Arrow Flash (USA, Europe).png",
    "Art Alive (World).png",
    "Art of Fighting (Europe).png",
    "Art of Fighting (USA).png",
    "Asterix and the Great Rescue (Europe) (En,Fr,De,Es,It).png",
    "Asterix and the Great Rescue (USA).png",
    "Asterix and the Power of the Gods (Europe) (Beta).png",
    "Asterix and the Power of the Gods (Europe) (En,Fr,De,Es).png",
    "Atomic Robo-Kid (Japan).png",
    "Atomic Robo-Kid (USA).png",
    "Atomic Runner (Europe).png",
    "Atomic Runner (USA).png",
    "ATP Tour (Europe).png",
    "ATP Tour Championship Tennis (USA).png",
    "Australian Rugby League (Europe).png",
    "Awesome Possum Kicks Dr Machino's Butt! (USA) (Beta).png",
    "Awesome Possum... ...Kicks Dr. Machino's Butt (Japan) (En).png",
    "Awesome Possum... ...Kicks Dr. Machino's Butt (USA).png",
    "Aworg (Japan) (SegaNet).png",
    "AWS Pro Moves Soccer (USA).png",
    "Ayrton Senna's Super Monaco GP II (Japan, Europe) (En,Ja).png",
    "Ayrton Senna's Super Monaco GP II (USA) (En,Ja).png",
    "B.O.B. (USA) (Beta).png",
    "B.O.B. (USA, Europe).png",
    "Baby's Day Out (USA) (Proto) (Earlier).png",
    "Baby's Day Out (USA) (Proto).png",
    "Back to the Future Part III (Europe).png",
    "Back to the Future Part III (USA).png",
    "Bad Omen (Japan, Korea).png",
    "Bahamut Senki (Japan).png",
    "Ball Jacks (Japan, Europe).png",
    "Ballz 3D - Fighting at Its Ballziest ~ Ballz 3D - The Battle of the Ballz (USA, Europe).png",
    "Barbie Super Model (USA) (Beta).png",
    "Barbie Super Model (USA).png",
    "Barbie Vacation Adventure (USA) (Proto).png",
    "Bare Knuckle - Ikari no Tetsuken ~ Streets of Rage (World) (Rev A).png",
    "Bare Knuckle - Ikari no Tetsuken ~ Streets of Rage (World).png",
    "Bare Knuckle II (Japan) (Beta).png",
    "Bare Knuckle II - Shitou e no Requiem ~ Streets of Rage II (Japan, Europe).png",
    "Bare Knuckle III (Japan).png",
    "Barkley Shut Up and Jam 2 (USA) (Beta).png",
    "Barkley Shut Up and Jam 2 (USA).png",
    "Barkley Shut Up and Jam! (USA, Europe).png",
    "Barney's Hide & Seek Game (USA).png",
    "Barver Battle Saga - Tai Kong Zhan Shi (China) (Unl).png",
    "Bass Masters Classic (USA).png",
    "Bass Masters Classic - Pro Edition (USA).png",
    "Batman (Europe).png",
    "Batman (Japan).png",
    "Batman - Revenge of the Joker (USA).png",
    "Batman - The Video Game (USA).png",
    "Batman Forever (World).png",
    "Batman Returns (World).png",
    "Battle Golfer Yui (Japan).png",
    "Battle Mania (Japan).png",
    "Battle Mania Daiginjou (Japan, Korea).png",
    "Battle Squadron (USA, Europe).png",
    "Battlemaster (USA).png",
    "BattleTech - A Game of Armored Combat (USA).png",
    "Battletoads (World).png",
    "Battletoads-Double Dragon (USA).png",
    "Beast Warriors (Japan).png",
    "Beast Wrestler (USA).png",
    "Beastball (World) (Proto).png",
    "Beauty and the Beast - Belle's Quest (USA).png",
    "Beauty and the Beast - Roar of the Beast (USA).png",
    "Beavis and Butt-Head (Europe).png",
    "Beavis and Butt-Head (USA) (Beta).png",
    "Beavis and Butt-Head (USA).png",
    "Beggar Prince (World) (Rev 1) (Unl).png",
    "Beggar Prince (World) (Unl).png",
    "Berenstain Bears' Camping Adventure, The (USA).png",
    "Best of the Best - Championship Karate (Europe).png",
    "Best of the Best - Championship Karate (USA).png",
    "Beyond Oasis (USA).png",
    "Beyond Zero Tolerance (USA) (Proto).png",
    "Bible Adventures (USA) (Unl).png",
    "Bill Walsh College Football (USA, Europe).png",
    "Bill Walsh College Football 95 (USA).png",
    "Bill's Tomato Game (USA) (Proto).png",
    "Bimini Run (USA).png",
    "Bio Hazard Battle (USA) (Beta).png",
    "Bio Hazard Battle (USA, Europe).png",
    "Bishoujo Senshi Sailor Moon (Japan).png",
    "Blades of Vengeance (USA, Europe).png",
    "Blaster Master 2 (USA) (Beta).png",
    "Blaster Master 2 (USA).png",
    "Blockbuster World Video Game Championship II (USA).png",
    "Blockout (World).png",
    "Bloodshot (Europe) (En,Fr,De,Es).png",
    "Blue Almanac (Japan).png",
    "Body Count (Brazil).png",
    "Body Count (Europe) (En,Fr,De,Es,It) (Beta).png",
    "Body Count (Europe) (En,Fr,De,Es,It).png",
    "Bomboy (Taiwan) (Unl).png",
    "Bonanza Bros. (Japan, Europe) (Rev A).png",
    "Bonanza Bros. (Japan, Europe).png",
    "Bonanza Bros. (World) (Rev B).png",
    "Bonkers (USA, Europe).png",
    "Boogerman - A Pick and Flick Adventure (Europe).png",
    "Boogerman - A Pick and Flick Adventure (USA).png",
    "Boogie Woogie Bowling (Japan).png",
    "Boxing Legends of the Ring (USA).png",
    "Bram Stoker's Dracula (Europe).png",
    "Bram Stoker's Dracula (USA).png",
    "Brett Hull Hockey '95 (USA).png",
    "Brian Lara Cricket (Europe) (June 1995).png",
    "Brian Lara Cricket (Europe) (March 1995).png",
    "Brian Lara Cricket 96 (Europe) (April 1996).png",
    "Brian Lara Cricket 96 (Europe) (March 1996).png",
    "Brutal - Paws of Fury (Europe) (En,Fr,De).png",
    "Brutal - Paws of Fury (USA).png",
    "Bubba 'N' Stix (Europe).png",
    "Bubba 'N' Stix (USA).png",
    "Bubba N Stix (Europe) (Beta).png",
    "Bubble and Squeak (Europe).png",
    "Bubble and Squeak (USA).png",
    "Bubsy II (USA, Europe).png",
    "Bubsy in - Claws Encounters of the Furred Kind (USA, Europe).png",
    "Buck Rogers - Countdown to Doomsday (USA, Europe).png",
    "Budokan - The Martial Spirit (Europe).png",
    "Budokan - The Martial Spirit (USA).png",
    "Bugs Bunny in Double Trouble (USA).png",
    "Bulls versus Blazers and the NBA Playoffs (USA, Europe).png",
    "Bulls vs Lakers and the NBA Playoffs (USA, Europe).png",
    "Burning Force (Europe).png",
    "Burning Force (Japan).png",
    "Burning Force (USA).png",
    "Cadash (USA, Korea).png",
    "Caesar no Yabou (Japan).png",
    "Caesar no Yabou II (Japan).png",
    "Caesars Palace (USA).png",
    "Cal Ripken Jr. Baseball (USA).png",
    "Caliber.50 (USA).png",
    "California Games (USA, Europe).png",
    "Cannon Fodder (Europe).png",
    "Captain America and the Avengers (Europe).png",
    "Captain America and the Avengers (USA) (Beta).png",
    "Captain America and the Avengers (USA).png",
    "Captain Lang (Japan) (En,Ja).png",
    "Captain Planet and the Planeteers (Europe).png",
    "Captain Planet and the Planeteers (USA).png",
    "Castle of Illusion - Fushigi no Oshiro Daibouken (Japan).png",
    "Castle of Illusion Starring Mickey Mouse (USA, Europe).png",
    "Castlevania - Bloodlines (USA).png",
    "Castlevania - The New Generation (Europe) (Beta).png",
    "Castlevania - The New Generation (Europe).png",
    "Centurion - Defender of Rome (USA, Europe).png",
    "Chakan (USA, Europe).png",
    "Chameleon Kid (Japan).png",
    "Champions World Class Soccer (World) (En,Fr,De,Es).png",
    "Championship Bowling (USA).png",
    "Championship Pool (USA).png",
    "Championship Pro-Am (USA).png",
    "Chao Ji Da Fu Weng (China) (Unl).png",
    "Chaos Engine 2, The (Europe) (Proto).png",
    "Chaos Engine, The (Europe).png",
    "Chase H.Q. II (USA).png",
    "Chavez II (USA).png",
    "Cheese Cat-Astrophe Starring Speedy Gonzales (Europe).png",
    "Chelnov (Japan).png",
    "Chester Cheetah - Too Cool to Fool (USA).png",
    "Chester Cheetah - Wild Wild Quest (USA).png",
    "Chi Chi's Pro Challenge Golf (USA).png",
    "Chibi Maruko-chan - Wakuwaku Shopping (Japan).png",
    "Chiki Chiki Boys (Japan, Korea).png",
    "Chiki Chiki Boys (USA, Europe).png",
    "Chou Kyuukai Miracle Nine (Japan).png",
    "Chou Touryuu Retsuden Dino Land (Japan).png",
    "Chuck Rock (Europe).png",
    "Chuck Rock (USA).png",
    "Chuck Rock II (Japan).png",
    "Chuck Rock II - Son of Chuck (Europe).png",
    "Chuck Rock II - Son of Chuck (USA) (Beta).png",
    "Chuck Rock II - Son of Chuck (USA).png",
    "Classic Collection (Europe).png",
    "Clay Fighter (Europe).png",
    "Clay Fighter (USA).png",
    "Cliffhanger (Europe).png",
    "Cliffhanger (USA).png",
    "Clue (USA).png",
    "Coach K College Basketball (USA).png",
    "College Football USA 96 (USA).png",
    "College Football USA 97 (USA).png",
    "College Football's National Championship (USA).png",
    "College Football's National Championship II (USA).png",
    "College Slam (USA).png",
    "Columns (World) (v1.1).png",
    "Columns (World).png",
    "Columns III (USA).png",
    "Columns III - Taiketsu! Columns World (Japan, Korea).png",
    "Combat Cars (USA, Europe).png",
    "Comix Zone (Europe) (En,Fr,De,Es).png",
    "Comix Zone (Japan).png",
    "Comix Zone (USA) (Beta).png",
    "Comix Zone (USA) (Sega Smash Pack).png",
    "Comix Zone (USA).png",
    "Congo (Unknown) (Proto).png",
    "Contra - Hard Corps (USA, Korea).png",
    "Contra - The Hard Corps (Japan).png",
    "Cool Spot (Europe).png",
    "Cool Spot (Japan, Korea).png",
    "Cool Spot (USA) (Beta).png",
    "Cool Spot (USA).png",
    "Corporation (Europe).png",
    "Cosmic Spacehead (USA, Europe) (En,Fr,De,Es).png",
    "Crack Down (Japan, Europe) (Rev A).png",
    "Crack Down (Japan, Europe).png",
    "Crack Down (USA).png",
    "Crayon Shin-chan - Arashi o Yobu Enji (Japan).png",
    "Cross Fire (USA).png",
    "Crude Buster (Japan).png",
    "Crue Ball (Japan).png",
    "Crue Ball - Heavy Metal Pinball (USA, Europe).png",
    "Crusader of Centy (USA).png",
    "Crying - Aseimei Sensou (Japan).png",
    "Crystal's Pony Tale (USA).png",
    "Curse (Japan).png",
    "Cutie Suzuki no Ringside Angel (Japan).png",
    "CutThroat Island (USA, Europe).png",
    "Cyber Police ESWAT (Japan).png",
    "Cyber-Cop (USA).png",
    "Cyberball (World).png",
    "Cyborg Justice (USA, Europe).png",
    "Daffy Duck in Hollywood (Europe) (Beta).png",
    "Daffy Duck in Hollywood (Europe) (En,Fr,De,Es,It).png",
    "Dahna (Korea).png",
    "Dahna - Megami Tanjou (Japan).png",
    "Daikoukai Jidai (Japan).png",
    "Daikoukai Jidai II (Japan).png",
    "Daimakai Mura (Japan).png",
    "Daisenpuu ~ Twin Hawk (Japan, Europe).png",
    "Dangerous Seed (Japan).png",
    "Darius II (Japan).png",
    "Dark Castle (USA, Europe).png",
    "Darwin 4081 (Japan, Korea).png",
    "Dashin' Desperadoes (USA) (Beta).png",
    "Dashin' Desperadoes (USA).png",
    "David Crane's Amazing Tennis (USA).png",
    "David Robinson Basketball (Japan).png",
    "David Robinson's Supreme Court (USA, Europe).png",
    "Davis Cup II (USA) (Proto).png",
    "Davis Cup Tennis (Japan).png",
    "Davis Cup Tennis ~ Davis Cup World Tour (USA, Europe) (July 1993).png",
    "Davis Cup Tennis ~ Davis Cup World Tour (USA, Europe) (June 1993).png",
    "Daze Before Christmas (Australia) (Beta).png",
    "Daze Before Christmas (Australia).png",
    "Deadly Moves (USA).png",
    "Death and Return of Superman, The (USA).png",
    "Death Duel (USA).png",
    "DEcapAttack (USA, Europe).png",
    "Demolition Man (USA) (Beta).png",
    "Demolition Man (USA, Europe).png",
    "Desert Demolition Starring Road Runner and Wile E. Coyote (USA, Europe).png",
    "Desert Strike - Return to the Gulf (USA, Europe).png",
    "Desert Strike - Wangan Sakusen ~ Desert Strike (Japan, Korea).png",
    "Devil Crash MD (Japan).png",
    "Devilish - The Next Possession (USA).png",
    "Dial Q o Mawase! (Japan) (Unl).png",
    "Dick Tracy (World).png",
    "Dick Vitale's 'Awesome, Baby!' College Hoops (USA).png",
    "Dino Dini's Soccer (Europe).png",
    "Dino Land (USA).png",
    "Dinosaur's Tale, A (USA).png",
    "Disney Collection, The - QuackShot Starring Donald Duck + Castle of Illusion Starring Mickey Mouse (Europe).png",
    "Divine Sealing (Japan) (Unl).png",
    "DJ Boy (Europe).png",
    "DJ Boy (Japan).png",
    "DJ Boy (USA).png",
    "Dominus (USA) (Proto).png",
    "Donald in Maui Mallard (Brazil).png",
    "Donald in Maui Mallard (Europe).png",
    "Dong Gu Ri Te Chi Jak Jeon (Korea).png",
    "Doom Troopers (USA).png",
    "Doraemon - Yume Dorobou to 7 Nin no Gozans (Japan).png",
    "Double Clutch (Europe).png",
    "Double Dragon (USA, Europe) (Unl).png",
    "Double Dragon 3 - The Arcade Game (USA, Europe).png",
    "Double Dragon II - The Revenge (Japan).png",
    "Double Dragon V - The Shadow Falls (USA).png",
    "Double Dribble - The Playoff Edition (USA).png",
    "Dr. Robotnik's Mean Bean Machine (Europe).png",
    "Dr. Robotnik's Mean Bean Machine (USA) (Beta).png",
    "Dr. Robotnik's Mean Bean Machine (USA).png",
    "Dragon - The Bruce Lee Story (Europe).png",
    "Dragon - The Bruce Lee Story (USA).png",
    "Dragon Ball Z - Buyuu Retsuden (Japan).png",
    "Dragon Ball Z - L'Appel du Destin (France).png",
    "Dragon Slayer - Eiyuu Densetsu (Japan).png",
    "Dragon Slayer - Eiyuu Densetsu II (Japan).png",
    "Dragon's Eye Plus - Shanghai III (Japan).png",
    "Dragon's Fury (USA, Europe).png",
    "Dragon's Lair (USA) (Proto).png",
    "Dragon's Revenge (Japan) (En).png",
    "Dragon's Revenge (USA, Europe).png",
    "Dream Team USA (Japan).png",
    "Duke Nukem 3D (Brazil).png",
    "Dune - The Battle for Arrakis (USA).png",
    "Dune II - Kampf um den Wuestenplaneten (Germany).png",
    "Dune II - The Battle for Arrakis (Europe).png",
    "Dungeons & Dragons - Warriors of the Eternal Sun (USA, Europe).png",
    "Dyna Brothers (Japan).png",
    "Dyna Brothers 2 (Japan).png",
    "Dyna Brothers 2 - Sega Channel Special (Japan) (Sega Channel).png",
    "Dynamite Duke (World) (Rev A).png",
    "Dynamite Duke (World).png",
    "Dynamite Headdy (Japan) (Beta).png",
    "Dynamite Headdy (Japan).png",
    "Dynamite Headdy (USA, Europe).png",
    "EA Hockey (Europe).png",
    "EA Hockey (Japan).png",
    "EA Sports Double Header (Europe).png",
    "Earnest Evans (USA).png",
    "Earth Defense (USA) (Unl).png",
    "Earthworm Jim (Europe).png",
    "Earthworm Jim (USA).png",
    "Earthworm Jim 2 (Europe).png",
    "Earthworm Jim 2 (USA).png",
    "Ecco - The Tides of Time (Europe).png",
    "Ecco - The Tides of Time (USA) (Beta).png",
    "Ecco - The Tides of Time (USA).png",
    "Ecco Jr. (USA, Australia) (February 1995).png",
    "Ecco Jr. (USA, Australia) (March 1995).png",
    "Ecco the Dolphin (Japan).png",
    "Ecco the Dolphin (USA, Europe).png",
    "Ecco the Dolphin II (Japan).png",
    "El. Viento (Japan).png",
    "El. Viento (USA).png",
    "Elemental Master (Japan).png",
    "Elemental Master (USA).png",
    "Elf Wor (China) (Unl).png",
    "Eliminate Down (Japan).png",
    "Elitserien 95 (Sweden).png",
    "Elitserien 96 (Sweden).png",
    "Empire of Steel (Europe).png",
    "ESPN Baseball Tonight (USA).png",
    "ESPN National Hockey Night (USA) (Beta).png",
    "ESPN National Hockey Night (USA).png",
    "ESPN Speed World (USA) (Beta).png",
    "ESPN Speed World (USA).png",
    "ESPN Sunday Night NFL (USA) (Beta).png",
    "ESPN Sunday Night NFL (USA).png",
    "ESWAT - City Under Siege (USA, Europe).png",
    "Eternal Champions (Europe) (Beta).png",
    "Eternal Champions (Europe).png",
    "Eternal Champions (Japan, Korea).png",
    "Eternal Champions (USA).png",
    "Europa Sensen (Japan).png",
    "European Club Soccer (Europe).png",
    "Evander Holyfield's 'Real Deal' Boxing (World).png",
    "Ex-Mutants (USA, Europe).png",
    "Ex-Ranza (Japan) (Beta).png",
    "Ex-Ranza (Japan).png",
    "Exile (USA).png",
    "Exile - Toki no Hazama he (Japan).png",
    "Exo Squad (Europe).png",
    "Exo Squad (USA) (Beta).png",
    "Exo Squad (USA).png",
    "Exodus - Journey to the Promised Land (USA) (Unl).png",
    "F-117 Night Storm (USA, Europe).png",
    "F-117 Stealth - Operation - Night Storm (Japan).png",
    "F-15 Strike Eagle II (Europe).png",
    "F-15 Strike Eagle II (USA) (Beta 1).png",
    "F-15 Strike Eagle II (USA) (Beta 2).png",
    "F-15 Strike Eagle II (USA).png",
    "F-22 Interceptor (Japan).png",
    "F-22 Interceptor (USA) (Beta).png",
    "F-22 Interceptor (USA, Europe) (June 1992).png",
    "F-22 Interceptor (USA, Europe) (September 1991).png",
    "F1 (Europe).png",
    "F1 - World Championship Edition (Europe) (Beta 1).png",
    "F1 - World Championship Edition (Europe) (Beta 2).png",
    "F1 - World Championship Edition (Europe).png",
    "F1 Circus MD (Japan).png",
    "Faery Tale Adventure, The (USA, Europe).png",
    "Family Feud (USA).png",
    "Fantasia (World) (Rev A).png",
    "Fantasia (World).png",
    "Fantastic Dizzy (USA, Europe) (En,Fr,De,Es,It).png",
    "Fastest 1 (Japan).png",
    "Fatal Fury (Europe).png",
    "Fatal Fury (USA).png",
    "Fatal Fury 2 (USA, Korea).png",
    "Fatal Labyrinth (USA, Europe).png",
    "Fatal Rewind (Europe).png",
    "Fatal Rewind (USA, Europe) (Rev A).png",
    "Fatman (Japan).png",
    "Feng Kuang Tao Hua Yuan (China) (Unl).png",
    "Feng Shen Ying Jie Chuan (China) (Unl).png",
    "Ferias Frustradas do Pica-Pau (Brazil).png",
    "Ferrari Grand Prix Challenge (Europe) (Rev A).png",
    "Ferrari Grand Prix Challenge (USA).png",
    "Fever Pitch Soccer (Europe) (En,Fr,De,Es,It).png",
    "Fido Dido (USA) (Proto).png",
    "FIFA 98 - Road to World Cup (Europe) (En,Fr,Es,It,Sv).png",
    "FIFA International Soccer (Japan) (En,Ja).png",
    "FIFA International Soccer (USA, Europe) (En,Fr,De,Es).png",
    "FIFA Soccer 95 (Korea) (En,Fr,De,Es).png",
    "FIFA Soccer 95 (USA, Europe) (En,Fr,De,Es).png",
    "FIFA Soccer 96 (USA, Europe) (En,Fr,De,Es,It,Sv).png",
    "FIFA Soccer 97 (USA, Europe) (En,Fr,De,Es,It,Sv).png",
    "Fighting Masters (Japan, Korea).png",
    "Fighting Masters (USA).png",
    "Final Blow (Japan).png",
    "Fire Mustang (Japan).png",
    "Fire Shark (Europe).png",
    "Fire Shark (USA).png",
    "Flash Point (Japan) (En) (Proto).png",
    "Flashback (Europe) (Rev A).png",
    "Flashback (Japan).png",
    "Flashback - The Quest for Identity (USA) (Alt 1).png",
    "Flashback - The Quest for Identity (USA).png",
    "Flicky (USA, Europe).png",
    "Flink (Europe).png",
    "Flintstones, The (Europe).png",
    "Flintstones, The (Japan).png",
    "Flintstones, The (USA).png",
    "Flux (Europe) (Requires MegaCD) (Program).png",
    "Foreman for Real (World).png",
    "Forgotten Worlds (World) (v1.1).png",
    "Forgotten Worlds (World).png",
    "Formula One (USA).png",
    "Frank Thomas Big Hurt Baseball (USA, Europe).png",
    "Frog Dude (USA) (Proto).png",
    "Frogger (USA).png",
    "From TV Animation Slam Dunk - Kyougou Makkou Taiketsu! (Japan).png",
    "Fun 'n Games (Europe).png",
    "Fun 'n' Games (USA).png",
    "Fun Car Rally (USA) (Proto).png",
    "Funny World & Balloon Boy (USA) (Unl).png",
    "Fushigi no Umi no Nadia (Japan).png",
    "FZ Senki Axis ~ Final Zone (Japan, USA).png",
    "G-LOC Air Battle (World) (Beta).png",
    "G-LOC Air Battle (World).png",
    "Gadget Twins (USA).png",
    "Gaiares (Japan, USA).png",
    "Gain Ground (World) (Alt 1).png",
    "Gain Ground (World) (Rev A).png",
    "Gain Ground (World).png",
    "Galaxy Force II (World) (Rev B).png",
    "Galaxy Force II (World).png",
    "Gambler Jiko Chuushinha - Katayama Masayuki no Mahjong Doujou (Japan).png",
    "Game Genie (USA, Europe) (Program).png",
    "Game Genie (USA, Europe) (Rev A) (Program).png",
    "Game no Kandume Otokuyou (Japan) (Sega Channel).png",
    "Game Toshokan (Japan) (Rev A) (Program).png",
    "Garfield - Caught in the Act (USA, Europe).png",
    "Gargoyles (USA).png",
    "Garou Densetsu - Shukumei no Tatakai (Japan).png",
    "Garou Densetsu 2 - Aratanaru Tatakai (Japan).png",
    "Garry Kitchen's Super Battletank - War in the Gulf (USA).png",
    "Gauntlet (Japan) (En,Ja).png",
    "Gauntlet IV (USA, Europe) (En,Ja) (August 1993).png",
    "Gauntlet IV (USA, Europe) (En,Ja) (September 1993).png",
    "Gemfire (USA).png",
    "General Chaos (USA, Europe).png",
    "General Chaos Daikonsen (Japan).png",
    "Generations Lost (USA, Europe).png",
    "Genghis Khan II - Clan of the Gray Wolf (USA).png",
    "George Foreman's KO Boxing (Europe).png",
    "George Foreman's KO Boxing (USA).png",
    "Ghostbusters (World) (v1.1).png",
    "Ghostbusters (World).png",
    "Ghouls'n Ghosts (USA, Europe) (Rev A).png",
    "Ghouls'n Ghosts (USA, Europe).png",
    "Global Gladiators (Europe).png",
    "GO-NET (Japan).png",
    "Gods (Europe).png",
    "Gods (Japan).png",
    "Gods (USA) (Beta).png",
    "Gods (USA).png",
    "Golden Axe (World) (Sega Smash Pack).png",
    "Golden Axe (World) (v1.1).png",
    "Golden Axe (World).png",
    "Golden Axe II (World) (Beta).png",
    "Golden Axe II (World).png",
    "Golden Axe III (Japan).png",
    "Goofy's Hysterical History Tour (USA).png",
    "Gouketsuji Ichizoku (Japan).png",
    "Granada (Japan, USA) (v1.1).png",
    "Granada (Japan, USA).png",
    "GrandSlam - The Tennis Tournament '92 (Japan).png",
    "GrandSlam - The Tennis Tournament (Europe).png",
    "Great Circus Mystery - Mickey to Minnie Magical Adventure 2 (Japan).png",
    "Great Circus Mystery Starring Mickey & Minnie, The (USA).png",
    "Great Waldo Search, The (USA).png",
    "Greatest Heavyweights (Europe).png",
    "Greatest Heavyweights (Japan).png",
    "Greatest Heavyweights (USA).png",
    "Greendog - The Beached Surfer Dude! (USA, Europe).png",
    "Grind Stormer (USA).png",
    "Growl (USA).png",
    "Gunfight 3 in 1 (World) (Unl).png",
    "Gunship (Europe).png",
    "Gunstar Heroes (Europe).png",
    "Gunstar Heroes (Japan) (Sample).png",
    "Gunstar Heroes (Japan).png",
    "Gunstar Heroes (USA).png",
    "Gynoug (Europe).png",
    "Gynoug (Japan).png",
    "Hard Drivin' (World).png",
    "HardBall '94 (USA, Europe).png",
    "HardBall '95 (USA).png",
    "HardBall III (USA) (Unl).png",
    "HardBall! (USA) (Unl).png",
    "Haunting Starring Polterguy (USA, Europe).png",
    "Havoc (Europe).png",
    "Head-On Soccer (USA).png",
    "Heavy Nova (USA).png",
    "Heavy Unit - Mega Drive Special (Japan).png",
    "Hei Tao 2 - Super Big 2 (China) (Unl).png",
    "Hellfire (Europe).png",
    "Hellfire (Japan).png",
    "Hellfire (USA).png",
    "Herzog Zwei (Japan).png",
    "Herzog Zwei (USA, Europe).png",
    "High Seas Havoc (USA).png",
    "Hit the Ice - VHL - The Official Video Hockey League (USA).png",
    "Hokuto no Ken - Shin Seikimatsu Kyuuseishu Densetsu (Japan).png",
    "Home Alone (USA) (Beta).png",
    "Home Alone (USA, Europe).png",
    "Home Alone 2 - Lost in New York (USA).png",
    "Honoo no Toukyuuji - Dodge Danpei (Japan).png",
    "Hook (Europe).png",
    "Hook (USA).png",
    "Hua Mu Lan - Mulan (China) (Unl).png",
    "Huan Le Tao Qi Shu - Smart Mouse (China) (Unl).png",
    "Humans, The (USA).png",
    "Hurricanes (Europe).png",
    "Hybrid Front, The (Japan) (Beta).png",
    "Hybrid Front, The (Japan).png",
    "Hyokkori Hyoutan-jima - Daitouryou wo Mezase! (Japan).png",
    "Hyper Dunk (Europe).png",
    "Hyper Dunk - The Playoff Edition (Japan) (Beta).png",
    "Hyper Dunk - The Playoff Edition (Japan).png",
    "Hyper Marbles (Japan) (SegaNet).png",
    "Ikasuze! Koi no Doki Doki Penguin Land MD (Japan) (SegaNet).png",
    "IMG International Tour Tennis (USA, Europe).png",
    "Immortal, The (USA, Europe).png",
    "Incredible Crash Dummies, The (USA) (Beta).png",
    "Incredible Crash Dummies, The (USA, Europe).png",
    "Incredible Hulk, The (USA, Europe).png",
    "Indiana Jones and the Last Crusade (Europe).png",
    "Indiana Jones and the Last Crusade (USA).png",
    "Insector X (Japan, Korea).png",
    "Insector X (USA).png",
    "Instruments of Chaos Starring Young Indiana Jones (USA) (Beta).png",
    "Instruments of Chaos Starring Young Indiana Jones (USA).png",
    "International Rugby (Europe).png",
    "International Superstar Soccer Deluxe (Europe).png",
    "Ishido - The Way of Stones (USA) (Unl).png",
    "It Came from the Desert (USA) (Proto).png",
    "Itchy & Scratchy Game, The (USA) (Proto).png",
    "Izzy's Quest for the Olympic Rings (USA, Europe).png",
    "J. League Champion Soccer (Japan).png",
    "J. League Pro Striker (Japan) (v1.0).png",
    "J. League Pro Striker (Japan) (v1.3).png",
    "J. League Pro Striker 2 (Japan).png",
    "J. League Pro Striker Perfect (Japan).png",
    "Jack Nicklaus' Power Challenge Golf (USA, Europe).png",
    "James 'Buster' Douglas Knockout Boxing (USA, Europe).png",
    "James Bond 007 - The Duel (Europe) (Rev A).png",
    "James Bond 007 - The Duel (USA).png",
    "James Pond - Underwater Agent (USA, Europe).png",
    "James Pond 3 (USA, Europe).png",
    "James Pond II (Japan, Korea).png",
    "James Pond II - Codename - Robocod (USA, Europe).png",
    "Jammit (USA).png",
    "Janou Touryuumon (Japan).png",
    "Jantei Monogatari (Japan).png",
    "Jashin Draxos (Japan, Korea).png",
    "Jelly Boy (Europe) (Proto).png",
    "Jennifer Capriati Tennis (USA).png",
    "Jeopardy! (USA).png",
    "Jeopardy! - Deluxe Edition (USA).png",
    "Jeopardy! - Sports Edition (USA).png",
    "Jerry Glanville's Pigskin Footbrawl (USA).png",
    "Jewel Master (Japan).png",
    "Jewel Master (USA, Europe) (Rev A).png",
    "Jim Power - The Arcade Game (USA) (Proto) [b].png",
    "Jimmy White's Whirlwind Snooker (Europe).png",
    "Jiu Ji Ma Jiang II - Ye Yan Bian (China) (Unl).png",
    "Joe & Mac (USA).png",
    "Joe Montana Football (World).png",
    "Joe Montana II Sports Talk Football (World) (Rev A).png",
    "Joe Montana II Sports Talk Football (World).png",
    "John Madden Football '92 (USA, Europe).png",
    "John Madden Football '93 (USA, Europe).png",
    "John Madden Football (USA, Europe).png",
    "John Madden Football - Championship Edition (USA).png",
    "John Madden Football - Pro Football (Japan).png",
    "Jordan vs Bird (USA, Europe) (v1.1).png",
    "Jordan vs Bird (USA, Europe).png",
    "Jordan vs Bird - One on One (Japan).png",
    "Joshua & the Battle of Jericho (USA) (Unl).png",
    "Judge Dredd (USA) (Beta) (Alt 1).png",
    "Judge Dredd (USA) (Beta).png",
    "Judge Dredd (World).png",
    "JuJu Densetsu ~ Toki - Going Ape Spit (World) (Rev A).png",
    "JuJu Densetsu ~ Toki - Going Ape Spit (World).png",
    "Junction (Japan, USA).png",
    "Jungle Book, The (Europe).png",
    "Jungle Book, The (USA).png",
    "Jungle Strike (USA) (Beta).png",
    "Jungle Strike (USA, Europe).png",
    "Jungle Strike - Uketsugareta Kyouki (Japan).png",
    "Junker's High (Japan) (Beta) [b].png",
    "Jurassic Park (Europe).png",
    "Jurassic Park (Japan).png",
    "Jurassic Park (USA) (Beta).png",
    "Jurassic Park (USA).png",
    "Jurassic Park - Rampage Edition (USA, Europe).png",
    "Justice League Task Force (World).png",
    "Juuouki (Japan) (v1.1).png",
    "Juuouki (Japan).png",
    "Juusou Kihei Leynos (Japan).png",
    "Ka-Ge-Ki (Japan).png",
    "Ka-Ge-Ki - Fists of Steel (USA).png",
    "Kawasaki Superbike Challenge (USA) (Beta).png",
    "Kawasaki Superbike Challenge (USA, Europe).png",
    "Kick Boxing, The (Japan, Korea).png",
    "Kick Off 3 - European Challenge (Europe).png",
    "Kid Chameleon (USA, Europe).png",
    "Kidou Keisatsu Patlabor - 98-Shiki Kidou Seyo! (Japan).png",
    "Killing Game Show, The (Japan).png",
    "King of the Monsters (Europe).png",
    "King of the Monsters (Japan).png",
    "King of the Monsters (USA).png",
    "King of the Monsters 2 (USA).png",
    "King Salmon (Japan).png",
    "King Salmon - The Big Catch (USA).png",
    "King's Bounty - The Conqueror's Quest (USA, Europe).png",
    "Kishi Densetsu (Japan).png",
    "Kiss Shot (Japan) (SegaNet).png",
    "Klax (Japan).png",
    "Klax (USA, Europe).png",
    "Koutetsu Teikoku (Japan).png",
    "Krusty's Super Fun House (USA, Europe) (v1.1).png",
    "Krusty's Super Fun House (USA, Europe).png",
    "Kujaku Ou 2 - Geneijou (Japan).png",
    "Kuuga - Operation Code 'Vapor Trail' (Japan).png",
    "Kyuukai Douchuuki (Japan).png",
    "Kyuukyoku Tiger (Japan).png",
    "La Russa Baseball 95 (USA, Australia).png",
    "Lakers versus Celtics and the NBA Playoffs (USA).png",
    "Landstalker (USA) (Beta).png",
    "Landstalker (USA).png",
    "Landstalker - Die Schatze von Konig Nolo (Germany).png",
    "Landstalker - Koutei no Zaihou (Japan).png",
    "Landstalker - Le Tresor du Roi Nole (France).png",
    "Landstalker - The Treasures of King Nole (Europe).png",
    "Langrisser (Japan).png",
    "Langrisser II (Japan) (v1.1).png",
    "Langrisser II (Japan) (v1.2).png",
    "Langrisser II (Japan).png",
    "Last Action Hero (USA, Europe).png",
    "Last Battle (USA, Europe).png",
    "Lawnmower Man, The (USA, Europe).png",
    "Legend of Galahad, The (USA, Europe).png",
    "Legend of Wukong (World) (Unl).png",
    "Legende de Thor, La (France).png",
    "Lemmings (Europe).png",
    "Lemmings (Japan, USA) (v1.1).png",
    "Lemmings (Japan, USA).png",
    "Lemmings 2 - The Tribes (Europe).png",
    "Lemmings 2 - The Tribes (USA).png",
    "Lethal Enforcers (Europe).png",
    "Lethal Enforcers (Japan).png",
    "Lethal Enforcers (USA) (Beta) (1993-08-13).png",
    "Lethal Enforcers (USA).png",
    "Lethal Enforcers II - Gun Fighters (Europe).png",
    "Lethal Enforcers II - Gun Fighters (USA).png",
    "LHX Attack Chopper (Japan).png",
    "LHX Attack Chopper (USA, Europe).png",
    "Liberty or Death (USA).png",
    "Light Crusader (Europe) (En,Fr,De,Es).png",
    "Light Crusader (Japan).png",
    "Light Crusader (Korea) (En,Ko).png",
    "Light Crusader (USA).png",
    "Lightening Force - Quest for the Darkstar (USA).png",
    "Lion King, The (World).png",
    "Lobo (USA) (Proto).png",
    "Long (China) (Unl).png",
    "Lord Monarch - Tokoton Sentou Densetsu (Japan).png",
    "Lost Vikings, The (Europe) (Beta).png",
    "Lost Vikings, The (Europe).png",
    "Lost Vikings, The (USA).png",
    "Lost World, The - Jurassic Park (USA, Europe).png",
    "Lotus II (USA) (Beta).png",
    "Lotus II (USA, Europe).png",
    "Lotus Turbo Challenge (USA, Europe).png",
    "Lufia & the Fortress of Doom (USA) (Proto).png",
    "M-1 Abrams Battle Tank (USA, Europe).png",
    "Ma Jiang Qing Ren - Ji Ma Jiang Zhi (China) (Unl).png",
    "Ma Qiao E Mo Ta - Devilish Mahjong Tower (China) (Unl).png",
    "Madden NFL '94 (USA, Europe).png",
    "Madden NFL 95 (USA, Europe).png",
    "Madden NFL 96 (USA, Europe).png",
    "Madden NFL 97 (USA, Europe).png",
    "Madden NFL 98 (USA).png",
    "Madou Monogatari I (Japan).png",
    "Magic School Bus, The (USA).png",
    "Magical Hat no Buttobi Turbo! Daibouken (Japan).png",
    "Magical Taruruuto-kun (Japan).png",
    "Mahjong Cop Ryuu - Shiro Ookami no Yabou (Japan).png",
    "Mamono Hunter Youko - Dai 7 no Keishou (Japan).png",
    "Man Overboard! (Europe).png",
    "Maou Renjishi (Japan).png",
    "Marble Madness (Japan).png",
    "Marble Madness (USA, Europe).png",
    "Mario Andretti Racing (USA, Europe).png",
    "Mario Lemieux Hockey (USA, Europe).png",
    "Marko (USA).png",
    "Marko's Magic Football (Europe) (En,Fr,De,Es) (Beta).png",
    "Marko's Magic Football (Europe) (En,Fr,De,Es).png",
    "Marsupilami (Europe) (En,Fr,De,Es,It).png",
    "Marsupilami (USA) (En,Fr,De,Es,It).png",
    "Marvel Land (Japan).png",
    "Marvel Land (USA).png",
    "Mary Shelley's Frankenstein (USA).png",
    "Master of Monsters (Japan).png",
    "Master of Monsters (USA).png",
    "Master of Weapon (Japan).png",
    "Maten no Soumetsu (Japan).png",
    "Math Blaster - Episode 1 (USA).png",
    "Mazin Saga (Asia).png",
    "Mazin Saga (Japan, Korea).png",
    "Mazin Saga - Mutant Fighter (USA).png",
    "Mazin Wars (Europe).png",
    "McDonald's Treasure Land Adventure (Europe).png",
    "McDonald's Treasure Land Adventure (Japan) (Beta).png",
    "McDonald's Treasure Land Adventure (Japan).png",
    "McDonald's Treasure Land Adventure (USA).png",
    "Medal City (Japan) (SegaNet).png",
    "Mega Anser (Japan) (Program).png",
    "Mega Bomberman (Europe).png",
    "Mega Bomberman (USA).png",
    "Mega Games 2 (Europe).png",
    "Mega Games 3 (Europe).png",
    "Mega Games 6 (Europe).png",
    "Mega Games 6 Vol. 2 (Europe).png",
    "Mega Games 6 Vol. 3 (Europe).png",
    "Mega Games I (Europe).png",
    "Mega lo Mania (Japan).png",
    "Mega Man - The Wily Wars (Europe).png",
    "Mega SWIV (Europe).png",
    "Mega Turrican (Europe).png",
    "Mega Turrican (USA).png",
    "Mega-lo-Mania (Europe) (v1.1).png",
    "Mega-lo-Mania (Europe).png",
    "Mega-lo-Mania (France).png",
    "MegaMind (Japan) (SegaNet).png",
    "MegaPanel (Japan).png",
    "MegaTrax (Japan).png",
    "Menacer 6-Game Cartridge (USA, Europe).png",
    "Meng Huan Shui Guo Pan - 777 Casino (China) (Unl).png",
    "Metal Fangs (Japan).png",
    "Michael Jackson's Moonwalker (World) (Rev A).png",
    "Michael Jackson's Moonwalker (World).png",
    "Mick & Mack as the Global Gladiators (USA) (Beta).png",
    "Mick & Mack as the Global Gladiators (USA).png",
    "Mickey Mania - The Timeless Adventures of Mickey Mouse (Europe).png",
    "Mickey Mania - The Timeless Adventures of Mickey Mouse (Japan).png",
    "Mickey Mania - The Timeless Adventures of Mickey Mouse (USA) (Beta).png",
    "Mickey Mania - The Timeless Adventures of Mickey Mouse (USA).png",
    "Mickey's Ultimate Challenge (USA).png",
    "Micro Machines (USA, Europe) (Alt 1).png",
    "Micro Machines (USA, Europe) (MDMM ACD3).png",
    "Micro Machines (USA, Europe).png",
    "Micro Machines 2 - Turbo Tournament (Europe) (J-Cart) (Alt 1).png",
    "Micro Machines 2 - Turbo Tournament (Europe) (J-Cart).png",
    "Micro Machines Military (Europe) (J-Cart).png",
    "Micro Machines Turbo Tournament 96 (Europe) (J-Cart).png",
    "Micro Machines Turbo Tournament 96 (Europe) (v1.1) (J-Cart).png",
    "Midnight Resistance (Japan).png",
    "Midnight Resistance (USA).png",
    "Midway Presents Arcade's Greatest Hits (Europe).png",
    "Mig-29 Fighter Pilot (Europe).png",
    "Mig-29 Fighter Pilot (Japan).png",
    "Mig-29 Fighter Pilot (USA).png",
    "Might and Magic - Gates to Another World (USA, Europe).png",
    "Might and Magic III - Isles of Terra (USA) (Proto).png",
    "Mighty Morphin Power Rangers (Europe).png",
    "Mighty Morphin Power Rangers (USA).png",
    "Mighty Morphin Power Rangers - The Movie (Europe).png",
    "Mighty Morphin Power Rangers - The Movie (USA).png",
    "Mike Ditka Power Football (USA, Europe) (Alt 1) (Unl).png",
    "Mike Ditka Power Football (USA, Europe) (Unl).png",
    "Minato no Traysia (Japan).png",
    "Minnesota Fats - Pool Legend (USA).png",
    "Miracle Piano Teaching System, The (USA).png",
    "MLBPA Baseball (USA).png",
    "Monopoly (USA) (Beta).png",
    "Monopoly (USA).png",
    "Monster World IV (Japan).png",
    "Monster World IV (USA, Europe) (En,Ja) (Virtual Console).png",
    "Mortal Kombat (World) (v1.1).png",
    "Mortal Kombat (World).png",
    "Mortal Kombat 3 (Europe).png",
    "Mortal Kombat 3 (USA).png",
    "Mortal Kombat II (World).png",
    "Mr. Nutz (Europe).png",
    "Mr. Nutz Hoppin' Mad (Europe) (Proto).png",
    "Ms. Pac-Man (USA, Europe).png",
    "Mugen Senshi Valis (Japan).png",
    "Muhammad Ali Heavyweight Boxing (Europe).png",
    "Muhammad Ali Heavyweight Boxing (USA) (Beta).png",
    "Muhammad Ali Heavyweight Boxing (USA).png",
    "MUSHA - Metallic Uniframe Super Hybrid Armor (USA).png",
    "Musha Aleste - Full Metal Fighter Ellinor (Japan).png",
    "Mutant League Football (Japan).png",
    "Mutant League Football (USA, Europe).png",
    "Mutant League Hockey (USA, Europe).png",
    "Mystic Defender (USA, Europe) (Rev A).png",
    "Mystic Defender (USA, Europe).png",
    "Mystical Fighter (USA).png",
    "Nakajima Satoru Kanshuu - F-1 Grand Prix (Japan).png",
    "Nakajima Satoru Kanshuu - F-1 Hero MD (Japan).png",
    "Nakajima Satoru Kanshuu - F-1 Super License (Japan).png",
    "NBA Action '94 (USA).png",
    "NBA Action '95 Starring David Robinson (USA, Europe).png",
    "NBA All-Star Challenge (USA, Europe).png",
    "NBA Hang Time (Europe).png",
    "NBA Hang Time (USA).png",
    "NBA Jam (Japan).png",
    "NBA Jam (USA, Europe) (v1.1).png",
    "NBA Jam (USA, Europe).png",
    "NBA Jam - Tournament Edition (World).png",
    "NBA Live 95 (Korea).png",
    "NBA Live 95 (USA, Europe).png",
    "NBA Live 96 (USA, Europe).png",
    "NBA Live 97 (USA, Europe).png",
    "NBA Live 98 (USA).png",
    "NBA Playoffs - Bulls vs Blazers (Japan).png",
    "NBA Pro Basketball '94 (Japan).png",
    "NBA Pro Basketball - Bulls vs Lakers (Japan).png",
    "NBA Showdown '94 (USA) (Unl) (Pirate).png",
    "NBA Showdown '94 (USA, Europe).png",
    "NCAA Final Four Basketball (USA).png",
    "NCAA Football (USA).png",
    "Nekketsu Koukou Dodgeball-bu - Soccer Hen MD (Japan).png",
    "New 3D Golf Simulation - Devil's Course (Japan).png",
    "New 3D Golf Simulation - Harukanaru Augusta (Japan).png",
    "New 3D Golf Simulation - Pebble Beach no Hatou (Japan).png",
    "New 3D Golf Simulation - Waialae no Kiseki (Japan).png",
    "New Horizons (USA).png",
    "New Zealand Story, The (Japan).png",
    "Newman Haas IndyCar featuring Nigel Mansell (World).png",
    "NFL '95 (USA, Europe).png",
    "NFL 98 (USA).png",
    "NFL Football '94 (Japan).png",
    "NFL Football '94 Starring Joe Montana (USA).png",
    "NFL Quarterback Club (World).png",
    "NFL Quarterback Club 96 (USA, Europe).png",
    "NFL Sports Talk Football '93 Starring Joe Montana (USA, Europe).png",
    "NHK Taiga Drama - Taiheiki (Japan).png",
    "NHL '94 (USA, Europe).png",
    "NHL 95 (USA, Europe).png",
    "NHL 96 (USA, Europe).png",
    "NHL 97 (USA, Europe).png",
    "NHL 98 (USA).png",
    "NHL All-Star Hockey '95 (USA).png",
    "NHL Hockey (USA).png",
    "NHLPA Hockey 93 (USA, Europe) (v1.1).png",
    "NHLPA Hockey 93 (USA, Europe).png",
    "Nigel Mansell's World Championship Racing (Europe).png",
    "Nigel Mansell's World Championship Racing (USA).png",
    "Nightmare Circus (Brazil) (Beta).png",
    "Nightmare Circus (Brazil).png",
    "Nikkan Sports Pro Yakyuu Van (Japan).png",
    "Ninja Burai Densetsu (Japan).png",
    "Ninja Gaiden (Japan) (Proto) [b].png",
    "No Escape (USA).png",
    "Nobunaga no Yabou - Bushou Fuuunroku (Japan).png",
    "Nobunaga no Yabou - Haouden (Japan).png",
    "Nobunaga no Yabou - Zenkoku Ban (Japan).png",
    "Nobunaga's Ambition (USA).png",
    "Normy's Beach Babe-O-Rama (USA, Europe).png",
    "Oh Mummy Genesis (World) (Unl).png",
    "Olympic Gold (Europe) (En,Fr,De,Es,It,Nl,Pt,Sv).png",
    "Olympic Gold (Japan, USA) (En,Fr,De,Es,It,Nl,Pt,Sv) (Rev A).png",
    "Olympic Gold (USA) (En,Fr,De,Es,It,Nl,Pt,Sv) (Alt 1).png",
    "Olympic Gold (USA) (En,Fr,De,Es,It,Nl,Pt,Sv).png",
    "Olympic Summer Games (USA, Europe).png",
    "On Dal Jang Goon (Korea).png",
    "Onslaught (USA, Europe) (Unl).png",
    "Ooze, The (Europe).png",
    "Ooze, The (Japan, USA).png",
    "Operation Europe - Path to Victory 1939-45 (USA).png",
    "Osomatsu-kun Hachamecha Gekijou (Japan).png",
    "Ottifants, The (Europe).png",
    "Ottifants, The (Germany) (Beta).png",
    "Out of this World (USA).png",
    "Outlander (Europe).png",
    "Outlander (USA).png",
    "OutRun (Japan).png",
    "OutRun (USA, Europe) (Sega Smash Pack).png",
    "OutRun (USA, Europe).png",
    "OutRun 2019 (Europe).png",
    "OutRun 2019 (Japan).png",
    "OutRun 2019 (USA) (Beta).png",
    "OutRun 2019 (USA).png",
    "OutRunners (Japan).png",
    "OutRunners (USA).png",
    "Ozaki Naomichi no Super Masters (Japan).png",
    "P.T.O. - Pacific Theater of Operations (USA).png",
    "Pac-Attack (USA).png",
    "Pac-Man 2 - The New Adventures (USA).png",
    "Pac-Mania (USA, Europe).png",
    "Pac-Panic (Europe).png",
    "Pachinko Kuunyan (Japan).png",
    "Paddle Fighter (Japan) (SegaNet).png",
    "Pagemaster, The (Europe).png",
    "Pagemaster, The (USA) (Beta).png",
    "Pagemaster, The (USA).png",
    "Panorama Cotton (Japan) (Beta) (1993-11-27).png",
    "Panorama Cotton (Japan).png",
    "Paperboy (Japan).png",
    "Paperboy (USA, Europe).png",
    "Paperboy 2 (USA, Europe).png",
    "Party Quiz Mega Q (Japan).png",
    "Pat Riley Basketball (USA).png",
    "Pebble Beach Golf Links (Europe).png",
    "Pebble Beach Golf Links (USA).png",
    "Pele II - World Tournament Soccer (USA, Europe).png",
    "Pele! (USA, Europe).png",
    "Pepenga Pengo (Japan).png",
    "Pete Sampras Tennis (USA, Europe) (J-Cart) (MDST6636).png",
    "Pete Sampras Tennis (USA, Europe) (J-Cart) (MDSTEE 13).png",
    "Pete Sampras Tennis (USA, Europe) (J-Cart).png",
    "PGA European Tour (USA, Europe).png",
    "PGA Tour 96 (USA, Europe).png",
    "PGA Tour Golf (USA, Europe) (v1.1).png",
    "PGA Tour Golf (USA, Europe) (v1.2).png",
    "PGA Tour Golf II (Japan).png",
    "PGA Tour Golf II (USA, Europe) (v1.1).png",
    "PGA Tour Golf II (USA, Europe).png",
    "PGA Tour Golf III (USA, Europe).png",
    "Phantasy Star - Sennenki no Owari ni (Japan).png",
    "Phantasy Star II (Brazil).png",
    "Phantasy Star II (USA, Europe) (Rev A).png",
    "Phantasy Star II (USA, Europe).png",
    "Phantasy Star II - Amia's Adventure (Japan) (SegaNet).png",
    "Phantasy Star II - Anne's Adventure (Japan) (SegaNet).png",
    "Phantasy Star II - Huey's Adventure (Japan) (SegaNet).png",
    "Phantasy Star II - Kaerazaru Toki no Owari ni (Japan).png",
    "Phantasy Star II - Kinds's Adventure (Japan) (SegaNet).png",
    "Phantasy Star II - Nei's Adventure (Japan) (SegaNet).png",
    "Phantasy Star II - Rudger's Adventure (Japan) (SegaNet).png",
    "Phantasy Star II - Shilka's Adventure (Japan) (SegaNet).png",
    "Phantasy Star II - Yushis's Adventure (Japan) (SegaNet).png",
    "Phantasy Star III - Generations of Doom (Brazil).png",
    "Phantasy Star III - Generations of Doom (USA, Europe).png",
    "Phantasy Star IV (Europe).png",
    "Phantasy Star IV (USA).png",
    "Phantom 2040 (Europe).png",
    "Phantom 2040 (USA).png",
    "Phelios (Europe).png",
    "Phelios (Japan).png",
    "Phelios (USA).png",
    "Pier Solar and the Great Architects (World) (Beta) (Unl).png",
    "Pier Solar and the Great Architects (World) (En,Es,Pt) (Rev C) (Unl).png",
    "Pier Solar and the Great Architects (World) (En,Fr,De) (Rev A) (Unl).png",
    "Pier Solar and the Great Architects (World) (En,Fr,De) (Rev B) (Unl).png",
    "Pier Solar and the Great Architects (World) (Unl).png",
    "Pink Goes to Hollywood (USA) (Beta).png",
    "Pink Goes to Hollywood (USA, Europe).png",
    "Pinocchio (Europe).png",
    "Pinocchio (USA).png",
    "Pirates of Dark Water, The (USA) (January 1994).png",
    "Pirates of Dark Water, The (USA, Europe) (May 1994).png",
    "Pirates! Gold (USA) (Beta).png",
    "Pirates! Gold (USA).png",
    "Pit-Fighter (World) (Rev A).png",
    "Pit-Fighter (World).png",
    "Pitfall - The Mayan Adventure (Europe).png",
    "Pitfall - The Mayan Adventure (USA).png",
    "Pocahontas (Europe).png",
    "Pocahontas (USA).png",
    "Populous (Europe).png",
    "Populous (Japan).png",
    "Populous (USA).png",
    "Power Athlete (Japan, Korea).png",
    "Power Drive (Europe) (En,Fr,De,Es,Pt).png",
    "Power Monger (Japan, Korea).png",
    "Power Monger (USA, Europe).png",
    "Powerball (USA).png",
    "Predator 2 (USA, Europe).png",
    "Premier Manager (Europe).png",
    "Premier Manager 97 (Europe).png",
    "Primal Rage (USA, Europe).png",
    "Prime Time NFL Starring Deion Sanders (USA).png",
    "Prince of Persia (Europe) (Beta) (Earlier).png",
    "Prince of Persia (Europe) (Beta).png",
    "Prince of Persia (Europe).png",
    "Prince of Persia (USA).png",
    "Prince of Persia 2 - The Shadow and the Flame (Europe) (Proto).png",
    "Pro Quarterback (USA).png",
    "Pro Striker Final Stage (Japan).png",
    "Pro Yakyuu Super League '91 (Japan).png",
    "Probotector (Europe) (En,Fr,De).png",
    "Psy-O-Blade (Japan).png",
    "Psycho Pinball (Europe) (En,Fr,De,Es,It) (October 1994).png",
    "Psycho Pinball (Europe) (En,Fr,De,Es,It) (September 1994).png",
    "Puggsy (Europe).png",
    "Puggsy (USA).png",
    "Pulseman (Japan).png",
    "Punisher, The (Europe).png",
    "Punisher, The (USA).png",
    "Putter Golf (Japan) (SegaNet).png",
    "Putty Squad (Europe) (Proto).png",
    "Puyo Puyo (Japan).png",
    "Puyo Puyo 2 (Japan) (v1.1).png",
    "Puyo Puyo 2 (Japan).png",
    "Puzzle & Action - Ichidanto-R (Japan).png",
    "Puzzle & Action - Tanto-R (Japan).png",
    "Pyramid Magic (Japan) (SegaNet).png",
    "Pyramid Magic II (Japan) (SegaNet).png",
    "Pyramid Magic III (Japan) (SegaNet).png",
    "Pyramid Magic Special (Japan) (SegaNet).png",
    "QuackShot Starring Donald Duck ~ QuackShot - I Love Donald Duck - Guruzia Ou no Hihou (World) (v1.1).png",
    "QuackShot Starring Donald Duck ~ QuackShot - I Love Donald Duck - Guruzia Ou no Hihou (World).png",
    "Quad Challenge (USA).png",
    "R.B.I. Baseball '93 (USA).png",
    "R.B.I. Baseball '94 (USA, Europe).png",
    "R.B.I. Baseball 3 (USA).png",
    "R.B.I. Baseball 4 (Japan).png",
    "R.B.I. Baseball 4 (USA).png",
    "Race Drivin' (USA).png",
    "Radical Rex (Europe).png",
    "Radical Rex (USA).png",
    "Ragnacenty (Korea).png",
    "Raiden Densetsu ~ Raiden Trad (Japan, USA).png",
    "Rainbow Islands Extra (Japan).png",
    "Rambo III (World) (v1.1).png",
    "Rambo III (World).png",
    "Rampart (Japan, Korea).png",
    "Rampart (USA).png",
    "Ranger X (Europe).png",
    "Ranger X (USA).png",
    "Ransei no Hasha (Japan).png",
    "Rastan Saga II (Japan).png",
    "Rastan Saga II (USA).png",
    "Red Zone (USA, Europe).png",
    "Ren & Stimpy Show Presents, The - Stimpy's Invention (Europe).png",
    "Ren & Stimpy Show Presents, The - Stimpy's Invention (USA) (Beta).png",
    "Ren & Stimpy Show Presents, The - Stimpy's Invention (USA).png",
    "Rent a Hero (Japan).png",
    "Resq (Europe) (Proto).png",
    "Revenge of Shinobi, The (Japan) (En) (Beta) (1989-03-XX) (Sega Smash Pack).png",
    "Revenge of Shinobi, The (USA, Europe) (Rev A).png",
    "Revenge of Shinobi, The (USA, Europe) (Rev B).png",
    "Revenge of Shinobi, The (USA, Europe).png",
    "Revenge of Shinobi, The (World) (Rev C) (Virtual Console).png",
    "Revolution X (USA, Europe).png",
    "Richard Scarry's Busytown (USA).png",
    "Riddle Wired (Japan) (SegaNet).png",
    "Rings of Power (USA, Europe).png",
    "Rise of the Robots (Europe).png",
    "Risk (USA).png",
    "Risky Woods (USA, Europe).png",
    "Ristar (USA, Europe) (August 1994).png",
    "Ristar (USA, Europe) (September 1994).png",
    "Ristar - The Shooting Star (Japan, Korea).png",
    "Road Rash (Japan).png",
    "Road Rash (USA, Europe).png",
    "Road Rash 3 (USA) (Alpha).png",
    "Road Rash 3 (USA, Europe).png",
    "Road Rash II (Japan).png",
    "Road Rash II (USA, Europe) (v1.2).png",
    "Road Rash II (USA, Europe).png",
    "RoadBlasters (Japan).png",
    "RoadBlasters (USA).png",
    "RoboCop 3 (USA, Europe).png",
    "RoboCop versus The Terminator (Europe) (Beta).png",
    "RoboCop versus The Terminator (Europe).png",
    "RoboCop versus The Terminator (Japan, Korea).png",
    "RoboCop versus The Terminator (USA).png",
    "Robot Battler (Japan) (SegaNet).png",
    "Robot Wreckage (USA) (Proto).png",
    "Rock 'n' Roll Racing (Europe).png",
    "Rock n' Roll Racing (USA).png",
    "Rocket Knight Adventures (Europe).png",
    "Rocket Knight Adventures (Japan).png",
    "Rocket Knight Adventures (USA) (Sample).png",
    "Rocket Knight Adventures (USA).png",
    "Rockman - Mega World (Japan) (Alt 1).png",
    "Rockman - Mega World (Japan).png",
    "Roger Clemens' MVP Baseball (USA).png",
    "Rolling Thunder 2 (Europe).png",
    "Rolling Thunder 2 (Japan).png",
    "Rolling Thunder 2 (USA).png",
    "Rolling Thunder 3 (USA).png",
    "Rolo to the Rescue (USA, Europe).png",
    "Romance of the Three Kingdoms II (USA).png",
    "Romance of the Three Kingdoms III - Dragon of Destiny (USA).png",
    "Royal Blood (Japan).png",
    "Rugby World Cup 95 (USA, Europe) (En,Fr,It).png",
    "Runark (Japan, Korea).png",
    "Ryuuko no Ken (Japan).png",
    "Sagaia (USA).png",
    "Saint Sword (Japan).png",
    "Saint Sword (USA).png",
    "Same! Same! Same! (Japan).png",
    "Sampras Tennis 96 (Europe) (J-Cart).png",
    "Samurai Shodown (Europe).png",
    "Samurai Shodown (USA).png",
    "Samurai Spirits (Japan).png",
    "San Guo Zhi Lie Zhuan - Luan Shi Qun Ying (China).png",
    "San Guo Zhi V (China) (Unl).png",
    "Sangokushi II (Japan).png",
    "Sangokushi III (Japan).png",
    "Sangokushi Retsuden - Ransei no Eiyuutachi (Japan).png",
    "Sansan (Japan).png",
    "Saturday Night Slammasters (Europe).png",
    "Saturday Night Slammasters (USA).png",
    "Scooby-Doo Mystery (USA).png",
    "Scrabble (Europe) (Proto).png",
    "SD Valis (Japan).png",
    "SeaQuest DSV (Europe).png",
    "SeaQuest DSV (USA).png",
    "Second Samurai (Europe).png",
    "Sega Sports 1 (Europe).png",
    "Sega Top Five (Brazil).png",
    "Senjou no Ookami II ~ Mercs (World).png",
    "Sensible Soccer (Europe) (En,Fr,De,It).png",
    "Sensible Soccer - International Edition (Europe) (En,Fr,De,It).png",
    "Sesame Street Counting Cafe (USA).png",
    "Shadow Blasters (USA).png",
    "Shadow Dancer - The Secret of Shinobi (World).png",
    "Shadow of the Beast (USA, Europe).png",
    "Shadow of the Beast - Mashou no Okite (Japan).png",
    "Shadow of the Beast II (USA, Europe).png",
    "Shadowrun (Japan).png",
    "Shadowrun (USA).png",
    "Shane Warne Cricket (Australia).png",
    "Shanghai II - Dragon's Eye (USA) (Beta).png",
    "Shanghai II - Dragon's Eye (USA).png",
    "Shaq-Fu (USA, Europe).png",
    "Shi Jie Zhi Bang Zheng Ba Zhan - World Pro Baseball 94 (China) (Unl).png",
    "Shi no Meikyuu - Labyrinth of Death (Japan) (SegaNet).png",
    "Shijou Saidai no Soukoban (Japan).png",
    "Shikinjou (Japan).png",
    "Shin Souseiki Ragnacenty (Japan).png",
    "Shining and the Darkness (Japan).png",
    "Shining Force (Europe).png",
    "Shining Force (USA) (Beta).png",
    "Shining Force (USA).png",
    "Shining Force - Kamigami no Isan (Japan).png",
    "Shining Force II (Europe).png",
    "Shining Force II (USA).png",
    "Shining Force II - Inishie no Fuuin (Japan).png",
    "Shining in the Darkness (Brazil).png",
    "Shining in the Darkness (USA, Europe).png",
    "Shinobi III - Return of the Ninja Master (Europe).png",
    "Shinobi III - Return of the Ninja Master (USA).png",
    "Shiten Myouou (Japan).png",
    "Shougi no Hoshi (Japan).png",
    "Shove It! ...The Warehouse Game (USA).png",
    "Show do Milhao (Brazil).png",
    "Show do Milhao Volume 2 (Brazil) (Alt 1).png",
    "Show do Milhao Volume 2 (Brazil).png",
    "Shui Hu - Feng Yun Zhuan (China) (Unl).png",
    "Shui Hu Zhuan (China) (Unl).png",
    "Shura no Mon (Japan).png",
    "Side Pocket (Europe).png",
    "Side Pocket (Japan).png",
    "Side Pocket (USA).png",
    "Simpsons, The - Bart vs. the Space Mutants (USA, Europe) (Rev A).png",
    "Simpsons, The - Bart vs. the Space Mutants (USA, Europe).png",
    "Simpsons, The - Bart's Nightmare (USA, Europe).png",
    "Skeleton Krew (Europe).png",
    "Skeleton Krew (USA).png",
    "Skitchin' (USA, Europe).png",
    "Slam - Shaq vs. the Legends (USA) (Proto).png",
    "Slap Fight MD (Japan).png",
    "Slaughter Sport (USA).png",
    "Slime World (Japan).png",
    "Smurfs Travel the World, The (Europe) (En,Fr,De,Es).png",
    "Smurfs, The (Europe) (En,Fr,De,Es,It) (Rev A).png",
    "Snake Rattle n Roll (Europe).png",
    "Snow Bros. - Nick & Tom (Japan).png",
    "Socket (USA).png",
    "Sol-Deace (USA).png",
    "Soldiers of Fortune (USA).png",
    "Soleil (Europe).png",
    "Soleil (France).png",
    "Soleil (Germany).png",
    "Soleil (Japan) (Beta).png",
    "Soleil (Spain).png",
    "Sonic & Knuckles (World).png",
    "Sonic & Knuckles + Sonic The Hedgehog (World).png",
    "Sonic & Knuckles + Sonic The Hedgehog 2 (World).png",
    "Sonic & Knuckles + Sonic The Hedgehog 3 (World).png",
    "Sonic 3D Blast (USA) (Beta).png",
    "Sonic 3D Blast ~ Sonic 3D Flickies' Island (USA, Europe).png",
    "Sonic Compilation (Europe).png",
    "Sonic Compilation ~ Sonic Classics (World) (v1.1).png",
    "Sonic Crackers (Japan) (Proto).png",
    "Sonic Eraser (Japan) (SegaNet).png",
    "Sonic Spinball (Japan).png",
    "Sonic The Hedgehog (Japan, Korea).png",
    "Sonic The Hedgehog (USA, Europe).png",
    "Sonic The Hedgehog (World) (GameCube Edition).png",
    "Sonic The Hedgehog 2 (World) (Beta 1).png",
    "Sonic The Hedgehog 2 (World) (Beta 2).png",
    "Sonic The Hedgehog 2 (World) (Rev A).png",
    "Sonic The Hedgehog 2 (World).png",
    "Sonic The Hedgehog 3 (Europe).png",
    "Sonic The Hedgehog 3 (Japan, Korea).png",
    "Sonic The Hedgehog 3 (USA).png",
    "Sonic The Hedgehog Spinball (Europe).png",
    "Sonic The Hedgehog Spinball (USA) (Alt 1).png",
    "Sonic The Hedgehog Spinball (USA) (Beta).png",
    "Sonic The Hedgehog Spinball (USA).png",
    "Sorcer Kingdom (Japan).png",
    "Sorcerer's Kingdom (USA) (v1.1).png",
    "Sorcerer's Kingdom (USA).png",
    "Sorcerian (Japan).png",
    "Space Funky B.O.B. (Japan).png",
    "Space Harrier II (Japan) (Launch Cart).png",
    "Space Harrier II (World).png",
    "Space Invaders '91 (USA).png",
    "Space Invaders 90 (Japan).png",
    "Sparkster (Europe).png",
    "Sparkster (USA).png",
    "Sparkster - Rocket Knight Adventures 2 (Japan).png",
    "Speedball 2 (Europe).png",
    "Speedball 2 (Japan).png",
    "Speedball 2 - Brutal Deluxe (USA).png",
    "Spider-Man (USA) (Acclaim) (Beta) (Earlier).png",
    "Spider-Man (USA) (Acclaim) (Beta).png",
    "Spider-Man (USA, Europe) (Acclaim).png",
    "Spider-Man (World) (Sega).png",
    "Spider-Man - X-Men - Arcade's Revenge (USA, Europe).png",
    "Spider-Man . Venom - Maximum Carnage (World).png",
    "Spiritual Warfare (USA) (Unl).png",
    "Spirou (Europe) (En,Fr,De,Es).png",
    "Splatterhouse 2 (Europe).png",
    "Splatterhouse 2 (USA).png",
    "Splatterhouse 3 (USA).png",
    "Splatterhouse Part 2 (Japan).png",
    "Splatterhouse Part 3 (Japan, Korea).png",
    "Sport Games (Brazil).png",
    "Sports Talk Baseball (USA).png",
    "Spot Goes to Hollywood (Europe).png",
    "Spot Goes to Hollywood (USA).png",
    "Squirrel King (China) (Unl).png",
    "Star Control (USA) (Unl).png",
    "Star Cruiser (Japan).png",
    "Star Odyssey (USA) (Beta) (1992-1-16).png",
    "Star Odyssey (World) (Unl).png",
    "Star Trek - Deep Space Nine - Crossroads of Time (Europe).png",
    "Star Trek - Deep Space Nine - Crossroads of Time (USA).png",
    "Star Trek - The Next Generation - Echoes from the Past (USA) (v1.1).png",
    "Star Trek - The Next Generation - Echoes from the Past (USA).png",
    "Starflight (USA, Europe) (v1.1).png",
    "Starflight (USA, Europe).png",
    "Stargate (Europe) (Beta).png",
    "Stargate (USA) (Sample) (NGen).png",
    "Stargate (USA, Europe).png",
    "Steel Empire (USA).png",
    "Steel Talons (Japan, Korea).png",
    "Steel Talons (USA) (Beta).png",
    "Steel Talons (USA, Europe).png",
    "Stone Protectors (USA) (Proto).png",
    "Stormlord (Japan).png",
    "Stormlord (USA).png",
    "Story of Thor, The (Europe).png",
    "Story of Thor, The (Germany).png",
    "Story of Thor, The (Japan) (Beta) [b].png",
    "Story of Thor, The (Korea).png",
    "Story of Thor, The (Spain).png",
    "Story of Thor, The - Hikari o Tsugumono (Japan).png",
    "Street Fighter II' - Special Champion Edition (Europe).png",
    "Street Fighter II' - Special Champion Edition (USA).png",
    "Street Fighter II' Plus - Champion Edition (Asia).png",
    "Street Racer (Europe).png",
    "Street Smart (Japan, USA).png",
    "Streets of Rage 2 (USA).png",
    "Streets of Rage 3 (Asia).png",
    "Streets of Rage 3 (Europe).png",
    "Streets of Rage 3 (USA).png",
    "Strider (USA, Europe).png",
    "Strider Hiryuu (Japan, Korea).png",
    "Strider II (Europe).png",
    "Strider Returns - Journey from Darkness (USA).png",
    "Striker (Europe) (Beta).png",
    "Striker (Europe).png",
    "Sub-Terrania (Europe).png",
    "Sub-Terrania (Japan).png",
    "Sub-Terrania (USA) (Beta) (Earlier).png",
    "Sub-Terrania (USA) (Beta).png",
    "Sub-Terrania (USA).png",
    "Summer Challenge (USA, Europe) (Unl).png",
    "Sunset Riders (Europe).png",
    "Sunset Riders (USA).png",
    "Super Airwolf (Japan).png",
    "Super Baseball 2020 (USA, Europe).png",
    "Super Battleship (USA).png",
    "Super Bubble Bobble (China) (Unl).png",
    "Super Daisenryaku (Japan) (Rev A).png",
    "Super Daisenryaku (Japan).png",
    "Super Fantasy Zone (Europe).png",
    "Super Fantasy Zone (Japan).png",
    "Super H.Q. (Japan).png",
    "Super Hang-On (World) (En,Ja) (Rev A).png",
    "Super Hang-On (World) (En,Ja).png",
    "Super Hang-On (World) (Sega Smash Pack).png",
    "Super High Impact (USA).png",
    "Super Hydlide (Europe).png",
    "Super Hydlide (Japan).png",
    "Super Hydlide (USA).png",
    "Super Kick Off (Europe).png",
    "Super League (Europe).png",
    "Super League (Japan).png",
    "Super Monaco GP (Japan) (En,Ja).png",
    "Super Monaco GP (Japan, Europe) (En,Ja) (Rev A).png",
    "Super Monaco GP (Japan, Europe) (En,Ja).png",
    "Super Monaco GP (USA) (En,Ja).png",
    "Super Off Road (USA, Europe) (Unl).png",
    "Super Real Basketball (Europe).png",
    "Super Real Basketball (Japan, Korea).png",
    "Super Shinobi II, The (Japan) (Beta) (Earlier).png",
    "Super Shinobi II, The (Japan) (Beta).png",
    "Super Shinobi II, The (Japan, Korea).png",
    "Super Shinobi, The (Japan).png",
    "Super Skidmarks (Europe) (Beta).png",
    "Super Skidmarks (Europe) (J-Cart).png",
    "Super Smash T.V. (USA, Europe).png",
    "Super Street Fighter II (Europe).png",
    "Super Street Fighter II (USA).png",
    "Super Street Fighter II - The New Challengers (Japan).png",
    "Super Thunder Blade (Japan) (Launch Cart).png",
    "Super Thunder Blade (World).png",
    "Super Volley Ball (Japan).png",
    "Super Volley Ball (USA).png",
    "Superman (USA) (Beta).png",
    "Superman (USA).png",
    "Superman - The Man of Steel (Europe).png",
    "Surging Aura (Japan).png",
    "Swamp Thing (USA) (Proto).png",
    "Sword of Sodan (Japan).png",
    "Sword of Sodan (USA, Europe).png",
    "Sword of Vermilion (USA, Europe).png",
    "Syd of Valis (USA).png",
    "Sylvester & Tweety in Cagey Capers (USA).png",
    "Sylvester and Tweety in Cagey Capers (USA) (Beta).png",
    "Syndicate (USA, Europe).png",
    "T2 - Terminator 2 - Judgment Day (USA, Europe).png",
    "T2 - The Arcade Game (Japan).png",
    "T2 - The Arcade Game (USA) (Beta).png",
    "T2 - The Arcade Game (USA, Europe).png",
    "Taikou Risshiden (Japan).png",
    "Taiwan Daheng (China) (Unl).png",
    "TaleSpin (USA, Europe).png",
    "Talmit's Adventure (Europe).png",
    "Target Earth (USA).png",
    "Task Force Harrier EX (Japan).png",
    "Task Force Harrier EX (USA).png",
    "Tatsujin ~ Truxton (World).png",
    "Taz in Escape from Mars (Europe).png",
    "Taz in Escape from Mars (USA).png",
    "Taz-Mania (World).png",
    "Team USA Basketball (USA, Europe).png",
    "TechnoClash (USA, Europe).png",
    "Technocop (USA) (Beta).png",
    "Technocop (USA).png",
    "Tecmo Cup (Japan) (Proto) [b].png",
    "Tecmo Super Baseball (USA).png",
    "Tecmo Super Bowl (Japan).png",
    "Tecmo Super Bowl (USA) (October 1993).png",
    "Tecmo Super Bowl (USA) (September 1993).png",
    "Tecmo Super Bowl II - Special Edition (Japan).png",
    "Tecmo Super Bowl II - Special Edition (USA).png",
    "Tecmo Super Bowl III - Final Edition (USA).png",
    "Tecmo Super Hockey (USA).png",
    "Tecmo Super NBA Basketball (Japan).png",
    "Tecmo Super NBA Basketball (USA).png",
    "Tecmo World Cup '92 (Japan).png",
    "Tecmo World Cup (USA).png",
    "Teddy Boy Blues (Japan) (SegaNet).png",
    "Teenage Mutant Hero Turtles - The Hyperstone Heist (Europe).png",
    "Teenage Mutant Hero Turtles - Tournament Fighters (Europe).png",
    "Teenage Mutant Ninja Turtles - Return of the Shredder (Japan).png",
    "Teenage Mutant Ninja Turtles - The Hyperstone Heist (USA).png",
    "Teenage Mutant Ninja Turtles - Tournament Fighters (Japan).png",
    "Teenage Mutant Ninja Turtles - Tournament Fighters (USA).png",
    "Teitoku no Ketsudan (Japan).png",
    "Tel-Tel Mahjong (Japan).png",
    "Tel-Tel Stadium (Japan).png",
    "Terminator, The (Europe).png",
    "Terminator, The (USA).png",
    "Test Drive II - The Duel (USA, Europe) (Unl).png",
    "Tetris (Japan).png",
    "Theme Park (USA, Europe).png",
    "Thomas the Tank Engine & Friends (USA).png",
    "Thunder Force II (USA, Europe).png",
    "Thunder Force II MD (Japan).png",
    "Thunder Force III (Japan, USA).png",
    "Thunder Force IV (Europe).png",
    "Thunder Force IV (Japan).png",
    "Thunder Fox (Japan).png",
    "Thunder Fox (USA).png",
    "Thunder Pro Wrestling Retsuden (Japan).png",
    "Tick, The (USA).png",
    "Time Dominator 1st (Japan, Korea).png",
    "Time Killers (Europe).png",
    "Time Killers (USA).png",
    "Time Trax (USA) (Proto).png",
    "TinHead (USA).png",
    "Tintin au Tibet (Europe) (En,Fr,De,Es,Nl,Sv).png",
    "Tiny Toon Adventures (Korea).png",
    "Tiny Toon Adventures - Acme All-Stars (Europe).png",
    "Tiny Toon Adventures - Acme All-Stars (USA, Korea).png",
    "Tiny Toon Adventures - Buster's Hidden Treasure (Europe).png",
    "Tiny Toon Adventures - Buster's Hidden Treasure (USA).png",
    "TNN Bass Tournament of Champions (USA).png",
    "TNN Outdoors Bass Tournament '96 (USA).png",
    "Todd's Adventures in Slime World (USA).png",
    "ToeJam & Earl (World) (Rev A).png",
    "ToeJam & Earl (World).png",
    "ToeJam & Earl in Panic auf Funkotron (Germany).png",
    "ToeJam & Earl in Panic on Funkotron (Europe).png",
    "ToeJam & Earl in Panic on Funkotron (Japan).png",
    "ToeJam & Earl in Panic on Funkotron (USA) (Beta).png",
    "ToeJam & Earl in Panic on Funkotron (USA).png",
    "Toki no Keishousha - Phantasy Star III (Japan).png",
    "Tom and Jerry - Frantic Antics (USA) (1993).png",
    "Tom and Jerry - Frantic Antics (USA) (1994).png",
    "Tom Mason's Dinosaurs for Hire (USA).png",
    "Tommy Lasorda Baseball (USA).png",
    "Tony La Russa Baseball (USA, Australia).png",
    "Top Gear 2 (USA).png",
    "Top Pro Golf (Japan).png",
    "Top Pro Golf 2 (Japan).png",
    "Total Football (Europe).png",
    "Toughman Contest (USA, Europe).png",
    "Tougiou King Colossus (Japan).png",
    "Toxic Crusaders (USA).png",
    "Toy Story (Europe).png",
    "Toy Story (USA) (Sample).png",
    "Toy Story (USA).png",
    "Toys (USA).png",
    "Trampoline Terror! (USA).png",
    "Traysia (USA).png",
    "Triple Play - Gold Edition (USA).png",
    "Triple Play 96 (USA).png",
    "Trouble Shooter (USA).png",
    "Troy Aikman NFL Football (USA).png",
    "True Lies (World).png",
    "Tun Shi Tian Di III (China) (Simple Chinese) (Unl).png",
    "Tun Shi Tian Di III (China) (Unl).png",
    "Turbo OutRun (Japan, Europe).png",
    "Turma da Monica na Terra dos Monstros (Brazil).png",
    "Turrican (USA, Europe) (Unl).png",
    "Twin Cobra - Desert Attack Helicopter (USA).png",
    "Twinkle Tale (Japan).png",
    "Twisted Flipper (USA) (Beta).png",
    "Two Crude Dudes (Europe).png",
    "Two Crude Dudes (USA).png",
    "Two Tribes - Populous II (Europe).png",
    "Tyrants - Fight through Time (USA).png",
    "Uchuu Senkan Gomora (Japan).png",
    "Ultimate Mortal Kombat 3 (Europe).png",
    "Ultimate Mortal Kombat 3 (USA).png",
    "Ultimate QIX (USA).png",
    "Ultimate Soccer (Europe) (En,Fr,De,Es,It) (Beta).png",
    "Ultimate Soccer (Europe) (En,Fr,De,Es,It).png",
    "Ultraman (Japan).png",
    "Uncharted Waters (USA).png",
    "Undead Line (Japan).png",
    "Universal Soldier (USA, Europe) (Unl).png",
    "Unnecessary Roughness '95 (USA).png",
    "Urban Strike (USA, Europe).png",
    "Uzu Keobukseon (Korea).png",
    "V-V (Japan).png",
    "Valis (USA).png",
    "Valis III (Japan) (Rev A).png",
    "Valis III (USA).png",
    "Vampire Killer (Japan).png",
    "Vapor Trail (USA).png",
    "Vectorman (USA) (Beta).png",
    "Vectorman (USA, Europe) (Sega Smash Pack).png",
    "Vectorman (USA, Europe).png",
    "Vectorman 2 (USA) (Beta).png",
    "Vectorman 2 (USA).png",
    "Venom . Spider-Man - Separation Anxiety (USA, Europe).png",
    "Vermilion (Japan).png",
    "Verytex (Japan).png",
    "Viewpoint (USA) (Beta).png",
    "Viewpoint (USA).png",
    "Virtua Fighter 2 (Korea).png",
    "Virtua Fighter 2 (USA, Europe).png",
    "Virtua Racing (Europe).png",
    "Virtua Racing (Japan).png",
    "Virtua Racing (USA).png",
    "Virtual Bart (World).png",
    "Virtual Pinball (USA, Europe).png",
    "Vixen 357 (Japan).png",
    "Volfied (Japan).png",
    "VR Troopers (USA, Europe).png",
    "Wacky Races (USA) (Proto).png",
    "Wacky Worlds Creativity Studio (USA).png",
    "Wani Wani World (Japan).png",
    "Wardner (USA).png",
    "Wardner no Mori Special (Japan).png",
    "Warlock (USA) (Beta).png",
    "Warlock (USA, Europe).png",
    "WarpSpeed (USA) (Unl).png",
    "Warrior of Rome (USA).png",
    "Warrior of Rome II (USA).png",
    "Warsong (USA).png",
    "Waterworld (Europe) (Proto).png",
    "Wayne Gretzky and the NHLPA All-Stars (USA, Europe).png",
    "Wayne's World (USA).png",
    "WeaponLord (USA).png",
    "Whac-a-Critter (USA) (Unl).png",
    "Wheel of Fortune (USA).png",
    "Where in the World Is Carmen Sandiego (Brazil) (Es,Pt).png",
    "Where in the World Is Carmen Sandiego (USA, Europe) (En,Fr,De,Es,It).png",
    "Where in Time Is Carmen Sandiego (Brazil) (Es,Pt).png",
    "Where in Time Is Carmen Sandiego (USA, Europe) (En,Fr,De,Es,It).png",
    "Whip Rush (USA).png",
    "Whip Rush - Wakusei Voltegas no Nazo (Japan).png",
    "Wild Snake (USA) (Proto).png",
    "Williams Arcade's Greatest Hits (USA).png",
    "Wimbledon Championship Tennis (Europe).png",
    "Wimbledon Championship Tennis (Japan).png",
    "Wimbledon Championship Tennis (USA) (Beta).png",
    "Wimbledon Championship Tennis (USA).png",
    "Wings of Wor (USA).png",
    "Winter Challenge (USA, Europe) (Rev 1).png",
    "Winter Challenge (USA, Europe).png",
    "Winter Olympic Games (USA) (En,Fr,De,Es,It,Pt,Sv,No).png",
    "Winter Olympics (Europe) (En,Fr,De,Es,It,Pt,Sv,No).png",
    "Winter Olympics (Japan) (En,Fr,De,Es,It,Pt,Sv,No).png",
    "Wiz'n'Liz (USA).png",
    "Wiz'n'Liz - The Frantic Wabbit Wescue (Europe).png",
    "Wizard of the Immortal (Japan).png",
    "Wolfchild (USA).png",
    "Wolverine - Adamantium Rage (USA, Europe).png",
    "Wonder Boy III - Monster Lair (Japan, Europe).png",
    "Wonder Boy in Monster World (USA, Europe).png",
    "Wonder Boy V - Monster World III (Japan, Korea).png",
    "World Championship Soccer II (Europe).png",
    "World Championship Soccer II (USA) (Beta).png",
    "World Championship Soccer II (USA).png",
    "World Class Leader Board (Europe).png",
    "World Class Leaderboard Golf (USA).png",
    "World Cup Italia '90 (Europe).png",
    "World Cup Soccer ~ World Championship Soccer (Japan, USA) (Rev B).png",
    "World Cup Soccer ~ World Championship Soccer (Japan, USA) (v1.2).png",
    "World Cup Soccer ~ World Championship Soccer (Japan, USA).png",
    "World Cup USA 94 (USA, Europe).png",
    "World Heroes (Japan).png",
    "World Heroes (USA).png",
    "World of Illusion - Fushigi na Magic Box (Japan) (Beta).png",
    "World of Illusion - Fushigi na Magic Box (Japan).png",
    "World of Illusion Starring Mickey Mouse and Donald Duck (Europe).png",
    "World of Illusion Starring Mickey Mouse and Donald Duck (USA, Korea).png",
    "World Series Baseball '95 (USA).png",
    "World Series Baseball '96 (USA).png",
    "World Series Baseball (USA).png",
    "World Series Baseball 98 (USA).png",
    "World Trophy Soccer (USA).png",
    "Worms (Europe) (Beta).png",
    "Worms (Europe).png",
    "Wrestle War (Japan) (Beta).png",
    "Wrestle War (Japan, Europe).png",
    "Wrestleball (Japan).png",
    "Wu Kong Wai Zhuan (China) (Unl).png",
    "WWF Raw (World).png",
    "WWF Royal Rumble (World).png",
    "WWF Super WrestleMania (USA, Europe).png",
    "WWF WrestleMania - The Arcade Game (USA) (Alpha).png",
    "WWF WrestleMania - The Arcade Game (USA, Europe).png",
    "X-Men (Europe).png",
    "X-Men (USA).png",
    "X-Men 2 - Clone Wars (USA, Europe).png",
    "X-Perts (USA).png",
    "XDR - X-Dazedly-Ray (Japan).png",
    "Xenon 2 - Megablast (Europe).png",
    "Xiao Monv - Magic Girl (China) (Unl).png",
    "Xin Qi Gai Wang Zi (China) (Alt 1) (Unl).png",
    "Xin Qi Gai Wang Zi (China) (Unl).png",
    "Ya Se Chuan Shuo (China) (Unl).png",
    "Yang Jia Jiang - Yang Warrior Family (China) (Unl).png",
    "Yogi Bear - Cartoon Capers (Europe).png",
    "Young Indiana Jones Chronicles, The (USA) (Proto).png",
    "Ys - Wanderers from Ys (Japan).png",
    "Ys III (USA).png",
    "Yu Yu Hakusho - Makyou Toitsusen (Japan).png",
    "Yu Yu Hakusho Gaiden (Japan).png",
    "YuYu Hakusho - Sunset Fighters (Brazil).png",
    "Zan Yasha Enbukyoku (Japan).png",
    "Zany Golf (USA, Europe) (v1.1).png",
    "Zany Golf (USA, Europe).png",
    "Zero the Kamikaze Squirrel (Europe).png",
    "Zero the Kamikaze Squirrel (USA).png",
    "Zero Tolerance (USA, Europe).png",
    "Zero Wing (Europe).png",
    "Zero Wing (Japan).png",
    "Zhuo Gui Da Shi - Ghost Hunter (China) (Unl).png",
    "Zombie High (USA) (Proto).png",
    "Zombies (Europe).png",
    "Zombies Ate My Neighbors (USA).png",
    "Zool - Ninja of the 'Nth' Dimension (Europe).png",
    "Zool - Ninja of the 'Nth' Dimension (USA).png",
    "Zoom! (World).png",
    "Zoop (Europe).png",
    "Zoop (USA).png",
    "Zou! Zou! Zou! Rescue Daisakusen (Japan).png",
  ];

  let transicaoAtiva = false;
  let intervalId;

  iniciarButton.addEventListener("click", function () {
    if (!transicaoAtiva) {
      transicaoAtiva = true;
      iniciarButton.disabled = true;
      pararButton.disabled = false;
      iniciarTransicao();
    }
  });

  pararButton.addEventListener("click", function () {
    if (transicaoAtiva) {
      transicaoAtiva = false;
      iniciarButton.disabled = false;
      pararButton.disabled = true;
      pararTransicao();
    }
  });

  reiniciarButton.addEventListener("click", function () {
    if (!transicaoAtiva) {
      imagemSorteada.style.display = "none";
    }
  });

  function iniciarTransicao() {
    intervalId = setInterval(function () {
      const numeroAleatorio = Math.floor(Math.random() * imagens.length);
      imagemSorteada.src = `./box2dfront/${imagens[numeroAleatorio]}`;
      imagemSorteada.style.display = "inline-block";
    }, 100);
  }

  function pararTransicao() {
    clearInterval(intervalId);
  }
});
